DROP TABLE Complaint;

DROP TABLE Case_Suspect;

DROP TABLE Case_Informant;

ALTER TABLE Investigation_Case
CHANGE COLUMN CID CID INT(10) NOT NULL AUTO_INCREMENT;

ALTER TABLE Investigation_Case
ADD COLUMN CaseNumber VARCHAR(10) NOT NULL AFTER UID;

ALTER TABLE Users
ADD COLUMN EmpID VARCHAR(10) NOT NULL AFTER Password;

CREATE TABLE Case_Suspect (
CSID INT(10) NOT NULL AUTO_INCREMENT,
CID INT(10) NOT NULL,
SID INT(10) NOT NULL,
PRIMARY KEY (CSID),
FOREIGN KEY (CID) REFERENCES Investigation_Case (CID),
FOREIGN KEY (SID) REFERENCES Suspect (SID));

CREATE TABLE Case_Informant (
CIID INT(10) NOT NULL AUTO_INCREMENT,
CID INT(10) NOT NULL,
IID INT(10) NOT NULL,
PRIMARY KEY (CIID),
FOREIGN KEY (CID) REFERENCES Investigation_Case (CID),
FOREIGN KEY (IID) REFERENCES Informant (IID));

CREATE TABLE Complaint (
CoID INT(10) NOT NULL AUTO_INCREMENT,
Date DATE NOT NULL,
Memo VARCHAR(500) NULL,
Status VARCHAR(20) NOT NULL,
UID INT(10) NOT NULL,
CID INT(10) NULL,
PRIMARY KEY (CoID),
FOREIGN KEY (UID) REFERENCES Users (UID),
FOREIGN KEY (CID) REFERENCES Investigation_Case (CID));
