-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 11:21:35 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema investigation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `investigation` DEFAULT CHARACTER SET latin1 ;
USE `investigation` ;

-- -----------------------------------------------------
-- Table `investigation`.`Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Permissions` (
  `PID` INT(10) NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`PID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Users` (
  `UID` INT(10) NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(20) NOT NULL,
  `Lname` VARCHAR(20) NOT NULL,
  `JobTitle` VARCHAR(50) NOT NULL,
  `PID` INT(10) NOT NULL,
  PRIMARY KEY (`UID`),
  INDEX `PID` (`PID` ASC),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`PID`)
    REFERENCES `investigation`.`Permissions` (`PID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Investigation_Case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Investigation_Case` (
  `CID` INT(10) NOT NULL,
  `Date` DATE NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `Memo` VARCHAR(500) NULL DEFAULT NULL,
  `Owner` VARCHAR(20) NOT NULL,
  `UID` INT(10) NOT NULL,
  PRIMARY KEY (`CID`),
  INDEX `UID` (`UID` ASC),
  CONSTRAINT `investigation_case_ibfk_1`
    FOREIGN KEY (`UID`)
    REFERENCES `investigation`.`Users` (`UID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Informant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Informant` (
  `IID` INT(10) NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(20) NOT NULL,
  `Lname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Case_Informant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Case_Informant` (
  `CIID` INT(10) NOT NULL AUTO_INCREMENT,
  `CID` INT(10) NOT NULL,
  `IID` INT(10) NOT NULL,
  PRIMARY KEY (`CIID`),
  INDEX `CID` (`CID` ASC),
  INDEX `IID` (`IID` ASC),
  CONSTRAINT `case_informant_ibfk_1`
    FOREIGN KEY (`CID`)
    REFERENCES `investigation`.`Investigation_Case` (`CID`),
  CONSTRAINT `case_informant_ibfk_2`
    FOREIGN KEY (`IID`)
    REFERENCES `investigation`.`Informant` (`IID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Suspect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Suspect` (
  `SID` INT(10) NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(20) NOT NULL,
  `Lname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`SID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Case_Suspect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Case_Suspect` (
  `CSID` INT(10) NOT NULL AUTO_INCREMENT,
  `CID` INT(10) NOT NULL,
  `SID` INT(10) NOT NULL,
  PRIMARY KEY (`CSID`),
  INDEX `CID` (`CID` ASC),
  INDEX `SID` (`SID` ASC),
  CONSTRAINT `case_suspect_ibfk_1`
    FOREIGN KEY (`CID`)
    REFERENCES `investigation`.`Investigation_Case` (`CID`),
  CONSTRAINT `case_suspect_ibfk_2`
    FOREIGN KEY (`SID`)
    REFERENCES `investigation`.`Suspect` (`SID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Complaint` (
  `CoID` INT(10) NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Memo` VARCHAR(500) NULL DEFAULT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `UID` INT(10) NOT NULL,
  `CID` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`CoID`),
  INDEX `UID` (`UID` ASC),
  INDEX `CID` (`CID` ASC),
  CONSTRAINT `complaint_ibfk_1`
    FOREIGN KEY (`UID`)
    REFERENCES `investigation`.`Users` (`UID`),
  CONSTRAINT `complaint_ibfk_2`
    FOREIGN KEY (`CID`)
    REFERENCES `investigation`.`Investigation_Case` (`CID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Source` (
  `SoID` INT(10) NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(20) NOT NULL,
  `Lname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`SoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `investigation`.`Complaint_Source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `investigation`.`Complaint_Source` (
  `CoSID` INT(10) NOT NULL AUTO_INCREMENT,
  `CoID` INT(10) NOT NULL,
  `SoID` INT(10) NOT NULL,
  PRIMARY KEY (`CoSID`),
  INDEX `CoID` (`CoID` ASC),
  INDEX `SoID` (`SoID` ASC),
  CONSTRAINT `complaint_source_ibfk_1`
    FOREIGN KEY (`CoID`)
    REFERENCES `investigation`.`Complaint` (`CoID`),
  CONSTRAINT `complaint_source_ibfk_2`
    FOREIGN KEY (`SoID`)
    REFERENCES `investigation`.`Source` (`SoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
